### PR TITLE
Feature/add system info

### PR DESCRIPTION
**Pull request by ksatirli**
This adds the `/info`, `/info?environment=1` and `/info?interfaces=1` endpoints, re-orders some of the tests and makes `loop-and-crash` globally available.

- [ ] bump version
- [ ] push to npmjs.org (Release It takes care of this)
- [ ] check if `.travis.yml` needs updating

### CODE REVIEW

**Review by ninjatux — COMMENTED** [review]
```js
var delay = function(req, res) {
  res.set('Content-Type', 'text/html');
  res.sendFile(path.join(__dirname + '/../delay.html'));
};

var delayWithDelay = function(req, res) {
  var delayTime = parseInt(req.params.delay);

  setTimeout(function() {
    res.sendStatus(200);
  }, (delayTime * 1000));
};
```

why one endpoint answers with a file and the other one sends back just the status code?

Why not having all the docs within a swagger api document and transform all the answers with a configurable format? eg:

```bash
"http://lac/delay"  # sends back just status code
"http://lac/delay?format=json" # send back request and response info as JSON object
```

anyway the PR does what it says adding the `info`endpoint 👍 ℹ️

**Comment by ksatirli** [comment]
Thanks for looking into this!

Happy to answer questions:

> why one endpoint answers with a file and the other one sends back just the status code?

So the idea is actually this: 
1.) if you go to `/delay`, you should see instructions on how to trigger a delay. 
2.) if you go to `/delay/5`, you should get a status 200 after five seconds.

Adding a Swagger spec to `loop-and-crash` sounds like a good idea. Are you offering a PR for this? 😄

**Comment by ksatirli** [comment]
> anyway the PR does what it says adding the infoendpoint 👍 ℹ️

Cool! I'll merge and create a new release soon. Will also make sure `loop-and-crash` gets pushed to npmjs.org and also that the `.travis.yml` gets updated. 

If you approve, can you also indicate so in the GitHub UI?

**Comment by ninjatux** [comment]
> So the idea is actually this:
> 1.) if you go to /delay, you should see instructions on how to trigger a delay.
> 2.) if you go to /delay/5, you should get a status 200 after five seconds.

I would give `/delay` a default behaviour as explained in a swagger api doc and then I would expose the endpoint options for customizing it. You could then remove the HTML docs (those have an expensive update process) and expose the Swagger docs behind endpoint.

Anyway I'll approve this PR and I'll prepare another one for the first Swagger file!

**Review by ninjatux — DISMISSED** [review]

**Review by ninjatux — APPROVED** [review]

**Pull request merged**
